# Generated by Django 2.0.7 on 2020-08-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20200807_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtitle',
            field=models.CharField(max_length=100, unique=True, verbose_name='商品名称'),
        ),
    ]
